services:
  imagesforadsdb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file:
      - path: ./.env
    environment:
      - CONN_STR=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    expose:
      - 27017
    ports:
      - 27017:27017
    external_links:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - type: bind
        source: ../data
        target: /data/db
